---
title: 'Introduction to R^[`r library(r2symbols) ; format(paste(symbol("copyright") , " - Wim R.M. Cardoen, 2022 - The content can neither be copied nor distributed without the **explicit** permission of the author."))`]'
subtitle: 'Section 6: Environments, Running R, Libraries and some probability distributions'
author: "Wim R.M. Cardoen"
date: "Last updated: `r format(Sys.time(), ' %2m/%2d/%Y @ %2H:%2M:%2S')`"
output:
  html_document:
    highlight: tango
    df_print: tibble
    toc: true
    toc_depth: 5
    number_sections: true
    mathjax: default
bibliography: [latex/intro.bib]
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
lang: en
---

# R Environments

*under construction*

# Running R

*under construction*

# R Packages

*under construction*

## Installation of R packages

## Using R packages

# Probability distributions

R comes with the most important probability distributions installed.
For the theoretical underpinnings, see e.g. [@CASELLA:2002a].

Probability distributions can be broadly classified into:

* discrete distributions
* continuous distributions

## Discrete distributions

Let $\mathbb{P}(X=k;\{\xi\})$ be a discrete probability mass function when the random variable $X=k$
and which depends on the parameter set $\{\xi\}$.
Let `keyword` be the (variable) name of the corresponding distribution. Then:

* **d**`keyword`$(k, \ldots)$: calculates the probability $\mathbb{P}(X=k)$
* **p**`keyword`$(k, \ldots)$: calculates the cumulative probability function (CDF) at $k$:
  $$F(X=k;\{\xi\}) := \sum_{j=0}^k \mathbb{P}(X=j)$$
* **q**`keyword`$(p, \ldots)$: calculates the value of $k$ where $p=F(k;\{\xi\})$ or
  $$k = \lceil F^{-1}(p;\{\xi\}) \rceil$$
* **r**`keyword`$(n, \ldots)$: generates a vector of $n$ random values sampled from the distribution `keyword`.

Some common discrete probability distributions implemented in R are listed below.

| `keyword` | Name | $\mathbb{P}(X=k;\{\xi\})$ | Parameter set ($\{\xi\}$) |
|:---|:---|:---|:---|
| `binom` | Binomial | $\displaystyle \binom{n}{k}p^k(1-p)^{n-k}$ | $0 \le p \le 1$ |
| `nbinom` | Negative Binomial | $\displaystyle \binom{k+r-1}{k}(1-p)^k p^r$ | $0 \le p \le 1$; $r>0$ |
| `hyper` | Hypergeometric | $\displaystyle \frac{\binom{K}{k}\binom{N-K}{n-k}}{\binom{N}{n}}$ | $N\in\{0,1,2,\dots\}$; $K,n\in\{0,1,\ldots,N\}$ |
| `pois` | Poisson | $\displaystyle \frac{\lambda^k\,e^{-\lambda}}{k!}$ | $0 < \lambda < \infty$ |

Table: Common discrete probability distributions.

### Examples

- Let's consider the following distribution: `binom`$(p=0.3, n=5)$.

  ```{R, echo=TRUE, comment=''}
  n <- 5
  p <- 0.3
  # Alternative code for the binom distribution
  mybinom <- function(n,p){
      v <- vector(mode="double", length=(n+1))
      for(k in 0:n){
        v[k+1] <- choose(n,k)*p^k*(1-p)^(n-k)  
      }
      return(v)
  }
  pvec <- mybinom(n,p)
  ```

  * Value of the PMF at $k=\{0,1,\ldots,5\}$:
    ```{R, echo=TRUE, comment=''}
    for(k in 0:n){
        cat(sprintf("  P(X=%d):%8.6f and should be %8.6f\n", 
                    k, dbinom(k, size=n, p), pvec[k+1]))
    }  
    ```

  * Value of the CDF at $k=\{0,1,\ldots,5\}$:
    ```{R, echo=TRUE, comment=''}
    for(k in 0:n){
        cat(sprintf("  F(X=%d):%8.6f and should be %8.6f\n", 
        k, pbinom(k,size=n,p), sum(pvec[1:(k+1)]) ))
    }  
    ```

  * The quantile function:
    ```{R, echo=TRUE, comment=''}
    pvec <- c(0.0, 0.25, 0.50, 0.75, 1.00)
    for(item in pvec){
        cat(sprintf("  P:%4.2f => k=%d\n", 
        item, qbinom(item,size=n, prob=p)))
    }
    ```

  * Sampling random numbers from the distribution:
    ```{R, echo=TRUE, comment=''}
    tot <- 15
    vec <- rbinom(tot,size=n, prob=p)
    print(vec)
    ```


## Continuous distributions

Let $f(x; \{\xi\})$ be a continuous probability density function (pdf), which depends on the
variable $x$ and the parameter set $\{\xi\}$.
Let `keyword` be the (variable) name of the corresponding distribution. Then:

* **d**`keyword`$(x, \ldots)$: calculates the value of the pdf at $x$, i.e. $f(x;\{\xi\})$
* **p**`keyword`$(x, \ldots)$: calculates the cumulative probability function (cdf) at $x$:
  $$F(x;\{\xi\}) := \int_{-\infty}^{x} f(t;\{\xi\})\, dt$$
* **q**`keyword`$(p, \ldots)$: calculates the value of $x$ where $p=F(x;\{\xi\})$ or
  $$x = F^{-1}(p;\{\xi\})$$
* **r**`keyword`$(n, \ldots)$: generates a vector of $n$ random values sampled from the distribution `keyword`.

Some common continuous probability distributions implemented in R are listed below.

| `keyword` | Name | $f(x;\{\xi\})$ | Domain($x$) | Parameter set ($\{\xi\}$) |
|:---|:---|:---|:---|:---|
| `unif` | Uniform | $\displaystyle \frac{1}{b-a}$ | $a \le x \le b$ | $a, b$ |
| `norm` | Normal | $\displaystyle \frac{1}{\sqrt{2\pi\sigma^2}}\exp\!\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)$ | $-\infty < x < \infty$ | $-\infty < \mu < \infty$, $\sigma > 0$ |
| `cauchy` | Cauchy | $\displaystyle \frac{1}{\pi\sigma}\frac{1}{1+\left(\frac{x-\theta}{\sigma}\right)^2}$ | $-\infty < x < \infty$ | $-\infty < \theta < \infty$, $\sigma > 0$ |
| `t` | Student's t | $\displaystyle \frac{\Gamma\!\left(\frac{\nu+1}{2}\right)}{\Gamma\!\left(\frac{\nu}{2}\right)}\frac{1}{\sqrt{\nu\pi}}\frac{1}{\left(1+\frac{x^2}{\nu}\right)^{(\nu+1)/2}}$ | $-\infty < x < \infty$ | $\nu=1,2,\ldots$ |
| `chisq` | Chi-squared | $\displaystyle \frac{1}{\Gamma(\nu/2)\,2^{\nu/2}}\,x^{(\nu/2)-1}e^{-x/2}$ | $0 \le x < \infty$ | $\nu=1,2,\ldots$ |
| `f` | F | $\displaystyle \frac{\Gamma\!\left(\frac{\nu_1+\nu_2}{2}\right)}{\Gamma\!\left(\frac{\nu_1}{2}\right)\Gamma\!\left(\frac{\nu_2}{2}\right)}\frac{x^{(\nu_1-2)/2}}{\left(1+\frac{\nu_1}{\nu_2}x\right)^{(\nu_1+\nu_2)/2}}$ | $0 \le x < \infty$ | $\nu_1,\nu_2=1,2,\ldots$ |
| `exp` | Exponential | $\displaystyle \lambda e^{-\lambda x}$ | $0 \le x < \infty$ | $\lambda > 0$ |

Table: Common continuous probability distributions.

where $\Gamma(x)$ stands for the gamma function which has the following mathematical form:

$$\Gamma(x) := \int_0^{\infty} t^{x-1} e^{-t} \, dt$$

### Examples

- Let's consider the following distribution: $N(\mu=5.0, \sigma^2=4.0)$, i.e. `distro`: `norm`.

  ```{R, echo=TRUE, comment=''}
  x <- 8.0
  mu <- 5.0
  sigma <- 2.0
  ```

  * Value of the PDF at $x$:
    ```{R, echo=TRUE, comment=''}
    cat(sprintf("The density at %f is %12.10f\n", x, dnorm(x,mean=mu, sd=sigma)))
    ```

  * Value of the CDF at $x$:
    ```{R, echo=TRUE, comment=''}
    prob <- pnorm(x,mean=mu,sd=sigma)
    cat(sprintf("The Cumulative Probability at %f is %12.10f", x, prob))
    ```

  * The quantile function:
    ```{R, echo=TRUE, comment=''}
    cat(sprintf("The point where the Cumulative Probability is %12.10f: %8.4f", 
                 prob, qnorm(prob, mean=mu, sd=sigma)))
    ```

  * Sampling random numbers from the distribution:
    ```{R, echo=TRUE, comment=''}
    vec <- rnorm(n=10, mean=mu, sd=sigma)
    print(vec)
    ```

## Exercises

1. Generate vectors with $10^4$, $10^5$, $10^6$, $10^7$ random numbers from the $\chi^2(\nu=5)$ distribution.
   Calculate the mean, as well as the variance for each of those vectors (`mean()`, `var()`).
   Note: If $X \sim \chi^2(\nu)$ $\Rightarrow$ $\mathbb{E}[X]=\nu$ and $\mathbb{V}[X]=2\nu$.

2. A brewer from the far-away lands of Hatu wants to follow the land's alcohol ordinance
   (i.e. a maximum of 5% ethanol per volume). In order to comply with the law he sent a batch
   of independent samples to a certified lab. The lab results are to be found in the file `data/beer.csv`.

   His plan is to perform a simple one-sided hypothesis test:

   $$H_0: \mu_0 = 5.0$$
   $$H_1: \mu \neq \mu_0$$

   He assumes that the alcohol % per volume is normally distributed (over the different
   samples/batches of beer) i.e. $N(\mu, \sigma^2)$ where $\mu$ is supposed to be $5.0$
   but where $\sigma^2$ is unknown.

   Let $c_{1-\alpha}$ be the (critical) point that separates the acceptance region
   ($\mathcal{A}$) with $\mathbb{P}(\mathcal{A})=1-\alpha$ from the rejection region
   ($\mathcal{R}$) with $\mathbb{P}(\mathcal{R})=\alpha$. Therefore:

   $$\alpha = \mathbb{P}(\overline{X} > c_{1-\alpha}\mid \mu=\mu_0)
            = \mathbb{P}\!\left(\frac{\overline{X}-\mu_0}{s/\sqrt{n}} > \frac{c_{1-\alpha}-\mu_0}{s/\sqrt{n}}\right)
            = \mathbb{P}\!\left(\frac{\overline{X}-\mu_0}{s/\sqrt{n}} > t_{1-\alpha}(\nu=n-1)\right)$$

   where $t$ stands for Student's t distribution, $s^2$ is the sample variance, and $n$ the
   number of measurements.

   * Read the lab results from the file `data/beer.csv`. (Hint: use `read.csv()` to read the file.)
   * Calculate the numerical value ($\tau$) of the test-statistic $T$, given by:
     $$T = \frac{\overline{X}-\mu_0}{s/\sqrt{n}} \;\sim\, t(\nu=n-1)$$
   * Determine $t_{0.95}(\nu=n-1)$, i.e. the critical point such that $\mathbb{P}(\mathcal{R})=0.05$.
   * Decide whether the brewer should reject $H_0$ (i.e. reject if $\tau > t_{0.95}(\nu=n-1)$).
   * What is the probability of the area under the curve for $t \in [\tau, +\infty)$?

3. Check out the following [link](https://higherlogicdownload.s3.amazonaws.com/AMSTAT/1484431b-3202-461e-b7e6-ebce10ca8bcd/UploadedImages/Classroom_Activities/HS_7__t-ditribution_and_GOSSET.pdf)
   if you are interested in the origin of Student's t distribution.

# Bibliography
